apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sigaint-website
  labels:
    app.kubernetes.io/name: sigaint-website
    app.kubernetes.io/component: web
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: sigaint.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sigaint-website
                port:
                  name: http